### ISSUE TITLE
How to download by resolution

### ISSUE THREAD

**Issue by z666666z** [GeekSpin/Wallhaven-scraper#29]
How to download such as 4K wallpaper resolution?

**Comment by Tempest042** [comment]
Here is a modified version of the code with options for ratio (i.e. 16x9) and options for minimum resolution (i.e. 3840x2160).

If you set the Minimum Resolution to 3840x2160 then every image it downloads will be atleast 4K.

[wallhaven-dl-resolution.txt](https://github.com/saurabhan/Wallhaven-dl/files/9372556/wallhaven-dl-resolution.txt) 

(Note: You may need to rename the file extension from .txt to .py)

Hope this helps.

**Comment by z666666z** [comment]
Thanks for your help!
